#!/usr/bin/env python3
"""Regenerate ADJUDICATION.md's LIVE OUTPUT block from the gates' actual
prints (Destroyer r9 prescription: numbers are generated, never typed).
Run after any edit; assemble.py refuses to build if the block is stale."""
import subprocess, re, pathlib, sys

ROOT = pathlib.Path(__file__).parent
ig = subprocess.run([sys.executable, ROOT / "image_gate.py"], capture_output=True, text=True).stdout
g2 = subprocess.run([sys.executable, ROOT / "gate_v2.py"], capture_output=True, text=True).stdout

ig_head = "\n".join(ig.splitlines()[:3])
suites = re.search(r"SUITE MEMBERSHIP.*?(?=\nDENSITY)", ig, re.S).group(0)
suite_counts = ", ".join(f"{m.group(1)} {m.group(2)}" for m in
                         re.finditer(r"^  (\S+) \((\d+)\):", suites, re.M))
density = re.search(r"DENSITY.*", ig, re.S).group(0).strip()
density_flags = "\n".join(l for l in density.splitlines()[1:] if l.strip()) or "  none over 3"
samehour = re.search(r"SAME-HOUR[^\n]*", ig).group(0)
g2_head = "\n".join(l for l in g2.splitlines() if l.startswith(("FLAGGED", "ALLOW entries",
                    "PHRASE_ALLOW")))
quota = "0 quota misses" if "MISS" not in g2 else "QUOTA MISSES PRESENT"

block = f"""<!-- GENERATED by sync_record.py — do not edit by hand -->
```
image_gate.py:
{ig_head}
{samehour}
suite counts: {suite_counts}
density flags (>3 in a 90-min window spanning 2+ hours):
{density_flags}

gate_v2.py:
{g2_head}
{quota}
```
<!-- END GENERATED -->"""

p = ROOT / "ADJUDICATION.md"
t = p.read_text()
t = re.sub(r"<!-- GENERATED by sync_record\.py.*?<!-- END GENERATED -->", block, t, flags=re.S)
p.write_text(t)
print("record block regenerated")
